/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import company.LoginFrame;
import company.Main;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2021
 */
public class BrandsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderInPanel
     */
    public BrandsPanel() {
        initComponents();
        LoginFrame.addPlaceHolderStyle(searchLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        searchLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();

        setMinimumSize(new java.awt.Dimension(935, 448));
        setPreferredSize(new java.awt.Dimension(935, 448));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 51, 255));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(900, 410));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setText("Brands");

        kButton1.setText("FIND ALL");
        kButton1.setBorderPainted(false);
        kButton1.setFocusPainted(false);
        kButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton1.setkBorderRadius(42);
        kButton1.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton1.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton1.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton1.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("DELETE");
        kButton2.setBorderPainted(false);
        kButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton2.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton2.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton2.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton2.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton2.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(387, 72));

        jLabel2.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jLabel2.setText("Search by :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));
        jComboBox1.setFocusable(false);
        jComboBox1.setMinimumSize(new java.awt.Dimension(71, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(71, 20));

        searchLabel.setBackground(new java.awt.Color(204, 204, 255));
        searchLabel.setText("Search");
        searchLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchLabelFocusLost(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Select From Table");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID :");

        idField.setEditable(false);
        idField.setBackground(new java.awt.Color(204, 204, 204));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name :");
        jLabel6.setMaximumSize(new java.awt.Dimension(48, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(48, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(48, 20));

        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        kButton3.setText("CLEAR");
        kButton3.setBorderPainted(false);
        kButton3.setFocusPainted(false);
        kButton3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton3.setkForeGround(new java.awt.Color(255, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton3.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton3.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton3.setMaximumSize(new java.awt.Dimension(111, 35));
        kButton3.setMinimumSize(new java.awt.Dimension(111, 35));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setText("UPDATE");
        kButton4.setBorderPainted(false);
        kButton4.setFocusPainted(false);
        kButton4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton4.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton4.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setText("ADD");
        kButton5.setBorderPainted(false);
        kButton5.setFocusPainted(false);
        kButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton5.setkBorderRadius(40);
        kButton5.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton5.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton5.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton5.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton5.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton5.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton5.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        try{
            findAllBrands();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "You must choose from the table", "Hint", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        BigDecimal id = (BigDecimal)dtm.getValueAt(jTable1.getSelectedRow(), 1);
        Connection con = null;
        PreparedStatement ps = null;
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            ps = con.prepareStatement("select id from products where brand_id = ?");
            ps.setBigDecimal(1, id);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "you can't delete this brand .. \n because it has products", "WARNING", JOptionPane.WARNING_MESSAGE);
                ps.close();
                con.close();
                return;
            }
            if(JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this brand ?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
                ps.close();
                con.close();
                return;
            }
            ps = con.prepareStatement("delete from brands where id = ?");
            ps.setBigDecimal(1, id);
            ps.executeUpdate();
            dtm.removeRow(jTable1.getSelectedRow());
            JOptionPane.showMessageDialog(this, "The brand was deleted .", "Done", JOptionPane.INFORMATION_MESSAGE);
            ps.close();
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel)this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        this.idField.setText((dtm.getValueAt(row, 1)).toString());
        this.nameField.setText((dtm.getValueAt(row, 2)).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusGained
        if(searchLabel.getText().equals("Search")){
            searchLabel.setText(null);
            searchLabel.requestFocus();
            LoginFrame.removePlaceHolderStyle(searchLabel);
        }
    }//GEN-LAST:event_searchLabelFocusGained

    private void searchLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusLost
        if(searchLabel.getText().length()==0){
            LoginFrame.addPlaceHolderStyle(searchLabel);
            searchLabel.setText("Search");
        }
    }//GEN-LAST:event_searchLabelFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String item = ((String)jComboBox1.getSelectedItem()).toLowerCase();
        String searchText = searchLabel.getText().trim().toLowerCase();
        ResultSet rs = null;
        PreparedStatement pstmt = null;
        Connection con = null;
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            switch(item){
                case "id":
                pstmt = con.prepareStatement("select id, name from brands where id = ?");
                pstmt.setLong(1, Long.parseLong(searchText));
                rs = pstmt.executeQuery();
                break;
                case "name":
                pstmt = con.prepareStatement("select id, name from brands where lower(name) like ?");
                pstmt.setString(1, "%"+searchText+"%");
                rs = pstmt.executeQuery();
                break;
            }
        }
        catch(SQLException e){e.printStackTrace(); JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);}
        catch(NumberFormatException e){System.err.println("NumberFormatException was caught .");}
        try{
            Main.buildTableModel(rs, jTable1);
            pstmt.close();
            con.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "nothing found");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        idField.setText("");
        nameField.setText("");
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        if(idField.getText().equals("")){JOptionPane.showMessageDialog(this, "Choose a brand from table", "Hint", JOptionPane.INFORMATION_MESSAGE); return; }
        Long id = Long.parseLong(idField.getText());
        String name = nameField.getText().trim();
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid name .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection con = null;
        PreparedStatement stmt = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            stmt = con.prepareStatement("select id from brands where lower(name) = ?");
            stmt.setString(1, name.toLowerCase());
            ResultSet rs = stmt.executeQuery();
            if(rs.next() && (rs.getLong(1) != id))
            {
                JOptionPane.showMessageDialog(this, "There is a brand with this name in the database .", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            stmt = con.prepareStatement("update brands set name = ? where id = ?");
            stmt.setString(1, name);
            stmt.setLong(2, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "The brand updated successfully .", "Done", JOptionPane.PLAIN_MESSAGE);
            findAllBrands();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        this.setVisible(false);
        Home.addBrandPanel.setVisible(true);
        Home.panelVisible = Home.addBrandPanel;
    }//GEN-LAST:event_kButton5ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        idField.setText("");
        nameField.setText("");
        try{
            findAllBrands();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void findAllBrands() throws SQLException{
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection con = DriverManager.getConnection(Main.URL);
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select id, name from brands");
        Main.buildTableModel(rs, jTable1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchLabel;
    // End of variables declaration//GEN-END:variables
}
