/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package company;

import static company.LoginFrame.addPlaceHolderStyle;
import static company.LoginFrame.removePlaceHolderStyle;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ProductsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductsPanel
     */
    public static ArrayList<Integer> brands_ids;
    public static ArrayList<String> brands_names;
    public static ArrayList<Integer> catagories_ids;
    public static ArrayList<String> catagories_names;
    public static JPanel layPanel;

    public ProductsPanel() {

        initComponents();

        LoginFrame.addPlaceHolderStyle(searchLabel);

        brands_ids = new ArrayList<Integer>();
        catagories_ids = new ArrayList<Integer>();
        brands_names = new ArrayList<String>();
        catagories_names = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        kPanel = new com.k33ptoo.components.KGradientPanel();
        scrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchLabel = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fromField = new javax.swing.JTextField();
        toField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kButton8 = new com.k33ptoo.components.KButton();
        kButton9 = new com.k33ptoo.components.KButton();
        idField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        kButton10 = new com.k33ptoo.components.KButton();
        catagoryCombo = new javax.swing.JComboBox<>();
        brandCombo = new javax.swing.JComboBox<>();
        kButton11 = new com.k33ptoo.components.KButton();

        setMinimumSize(new java.awt.Dimension(935, 448));
        setPreferredSize(new java.awt.Dimension(935, 448));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        kPanel.setkEndColor(new java.awt.Color(0, 51, 255));
        kPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kPanelFocusGained(evt);
            }
        });
        kPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kPanelMouseClicked(evt);
            }
        });

        scrollPane.setDoubleBuffered(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "Name", "Catagory", "Brand", "Color", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        scrollPane.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setText("Products");

        kButton4.setForeground(new java.awt.Color(255, 51, 51));
        kButton4.setText("QUANTITIES");
        kButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton4.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton4.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton4.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setForeground(new java.awt.Color(255, 51, 51));
        kButton5.setText("UPDATE");
        kButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton5.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton5.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton5.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton5.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton5.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton5.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton6.setForeground(new java.awt.Color(255, 51, 51));
        kButton6.setText("DELETE");
        kButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton6.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton6.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton6.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton6.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton6.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton6.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton7.setForeground(new java.awt.Color(255, 51, 51));
        kButton7.setText("ADD");
        kButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton7.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton7.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton7.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton7.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton7.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        searchLabel.setBackground(new java.awt.Color(204, 204, 255));
        searchLabel.setText("Search");
        searchLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchLabelFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Catagory", "Brand", "Color", "Price" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jLabel2.setText("Search by :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Find products with price ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("from :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("to :");

        fromField.setBackground(new java.awt.Color(102, 102, 255));
        fromField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        fromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFieldActionPerformed(evt);
            }
        });

        toField.setBackground(new java.awt.Color(102, 102, 255));
        toField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("$");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("$");

        kButton8.setForeground(new java.awt.Color(255, 51, 51));
        kButton8.setText("FIND");
        kButton8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton8.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton8.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton8.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton8.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton8.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton8.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });

        kButton9.setForeground(new java.awt.Color(255, 51, 51));
        kButton9.setText("FIND ALL");
        kButton9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton9.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton9.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton9.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton9.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton9.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton9.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton9.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });

        idField.setEditable(false);
        idField.setBackground(new java.awt.Color(204, 204, 204));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("ID :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Name :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Brand :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Catagory :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Price :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Color :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 255, 51));
        jLabel16.setText("Select from table ");

        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        colorField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        priceField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        kButton10.setForeground(new java.awt.Color(255, 51, 51));
        kButton10.setText("Clear");
        kButton10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton10.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton10.setkForeGround(new java.awt.Color(255, 0, 0));
        kButton10.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton10.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton10.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton10.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });

        kButton11.setForeground(new java.awt.Color(255, 51, 51));
        kButton11.setText("Report");
        kButton11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kButton11.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton11.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton11.setkHoverEndColor(new java.awt.Color(51, 51, 0));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton11.setkHoverStartColor(new java.awt.Color(102, 255, 204));
        kButton11.setkSelectedColor(new java.awt.Color(51, 204, 255));
        kButton11.setkStartColor(new java.awt.Color(255, 204, 51));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kPanelLayout = new javax.swing.GroupLayout(kPanel);
        kPanel.setLayout(kPanelLayout);
        kPanelLayout.setHorizontalGroup(
            kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelLayout.createSequentialGroup()
                .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kPanelLayout.createSequentialGroup()
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelLayout.createSequentialGroup()
                                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(colorField)
                                            .addComponent(priceField)
                                            .addComponent(catagoryCombo, 0, 169, Short.MAX_VALUE)
                                            .addComponent(brandCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(kButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kPanelLayout.createSequentialGroup()
                                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        kPanelLayout.setVerticalGroup(
            kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(kButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kPanelLayout.createSequentialGroup()
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(catagoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(brandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelLayout.createSequentialGroup()
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(kPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        this.setVisible(false);
        Home.addProductsPanel.setVisible(true);
        Home.panelVisible = Home.addProductsPanel;
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        if (row == -1) {
            return;
        }
        BigDecimal id = (BigDecimal) dtm.getValueAt(row, 1);
        String name = (String) dtm.getValueAt(row, 2);
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + name + " product ?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            PreparedStatement stmt = con.prepareStatement("delete from products where id = ?");
            stmt.setBigDecimal(1, id);
            stmt.executeUpdate();
            dtm.removeRow(row);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        if (idField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Choose a product from table", "Hint", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Long id = Long.parseLong(idField.getText());
        String name = nameField.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid name .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int catagory = catagories_ids.get(catagoryCombo.getSelectedIndex());
        if (catagory == -1) {
            JOptionPane.showMessageDialog(this, "Invalid catagory .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int brand = brands_ids.get(brandCombo.getSelectedIndex());
        if (brand == -1) {
            JOptionPane.showMessageDialog(this, "Invalid brand .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String color = colorField.getText();

        Connection con = null;
        PreparedStatement stmt = null;
        try {
            Float price = Float.parseFloat(priceField.getText());
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            stmt = con.prepareStatement("update products set name = ?, catagory_id = ?, brand_id = ?, color = ?, price = ? where id = ?");
            stmt.setString(1, name);
            stmt.setInt(2, catagory);
            stmt.setInt(3, brand);
            stmt.setString(4, color);
            stmt.setFloat(5, price);
            stmt.setLong(6, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "The product updated successfully .", "Done", JOptionPane.PLAIN_MESSAGE);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        DefaultTableModel dtm1 = (DefaultTableModel) this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        if (row == -1) {
            return;
        }
        BigDecimal id = (BigDecimal) dtm1.getValueAt(row, 1);
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            PreparedStatement stmt = con.prepareStatement("select stores.warehouse_id, warehouses.location, stores.quantity "
                    + "from stores, warehouses where stores.warehouse_id = warehouses.id and stores.product_id = ?");
            stmt.setBigDecimal(1, id);
            ResultSet rs = stmt.executeQuery();
            ProductQuantityPanel quantityPanel = new ProductQuantityPanel();
            Main.buildTableModel(rs, quantityPanel.table);
            int total = 0;
            stmt = con.prepareStatement("select sum(quantity) from stores where product_id = ? group by product_id");
            stmt.setBigDecimal(1, id);
            rs = stmt.executeQuery();
            if (rs.next()) {
                total = rs.getInt(1);
            }
            quantityPanel.label.setText(total + "");
            Home.glassPane.add(quantityPanel);
            Home.glassPane.setVisible(true);
            stmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void fromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFieldActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        fromField.setBorder(new LineBorder(new Color(204, 204, 255), 1));
        toField.setBorder(new LineBorder(new Color(204, 204, 255), 1));
        String from = fromField.getText().trim();
        String to = toField.getText().trim();
        if (from.equals("")) {
            fromField.setBorder(new LineBorder(Color.red, 1));
            return;
        } else if (to.equals("")) {
            toField.setBorder(new LineBorder(Color.red, 1));
            return;
        }
        try {
            Float f, t;
            try {
                f = Float.parseFloat(from);
            } catch (NumberFormatException e) {
                fromField.setBorder(new LineBorder(Color.red, 1));
                return;
            }
            try {
                t = Float.parseFloat(to);
            } catch (NumberFormatException e) {
                toField.setBorder(new LineBorder(Color.red, 1));
                return;
            }
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            PreparedStatement pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                    + " brands.name, products.color, products.price from products, brands, catagories "
                    + "where products.brand_id = brands.id and products.catagory_id = catagories.id and products.price between ? and ?");
            pstmt.setFloat(1, f);
            pstmt.setFloat(2, t);
            ResultSet rs = pstmt.executeQuery();
            Main.buildTableModel(rs, jTable1);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton8ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String item = ((String) jComboBox1.getSelectedItem()).toLowerCase();
        String searchText = searchLabel.getText().trim().toLowerCase();
        ResultSet rs = null;
        PreparedStatement pstmt = null;
        Connection con = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            switch (item) {
                case "id":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and products.id = ?");
                    pstmt.setLong(1, Long.parseLong(searchText));
                    rs = pstmt.executeQuery();
                    break;
                case "name":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and lower(products.name) like ?");
                    pstmt.setString(1, "%" + searchText + "%");
                    rs = pstmt.executeQuery();
                    break;
                case "catagory":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and lower(catagories.name) like ?");
                    pstmt.setString(1, "%" + searchText + "%");
                    rs = pstmt.executeQuery();
                    break;
                case "brand":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and lower(brands.name) like ?");
                    pstmt.setString(1, "%" + searchText + "%");
                    rs = pstmt.executeQuery();
                    break;
                case "color":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and lower(products.color) like ?");
                    pstmt.setString(1, "%" + searchText + "%");
                    rs = pstmt.executeQuery();
                    break;
                case "price":
                    pstmt = con.prepareStatement("select products.id, products.name, catagories.name,"
                            + " brands.name, products.color, products.price from products, brands, catagories "
                            + "where products.brand_id = brands.id and products.catagory_id = catagories.id and products.price = ?");
                    pstmt.setInt(1, Integer.parseInt(searchText));
                    rs = pstmt.executeQuery();
                    break;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            System.err.println("NumberFormatException was caught .");
        }
        try {
            Main.buildTableModel(rs, jTable1);
            pstmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "nothing found");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        try {
            findAllProducts();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton9ActionPerformed

    private void searchLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusGained
        if (searchLabel.getText().equals("Search")) {
            searchLabel.setText(null);
            searchLabel.requestFocus();
            removePlaceHolderStyle(searchLabel);
        }
    }//GEN-LAST:event_searchLabelFocusGained

    private void searchLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusLost
        if (searchLabel.getText().length() == 0) {
            addPlaceHolderStyle(searchLabel);
            searchLabel.setText("Search");
        }
    }//GEN-LAST:event_searchLabelFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.requestFocusInWindow();
    }//GEN-LAST:event_formFocusGained

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        this.idField.setText((dtm.getValueAt(row, 1)).toString());
        this.nameField.setText((dtm.getValueAt(row, 2)).toString());
        this.catagoryCombo.setSelectedItem((String) dtm.getValueAt(row, 3));
        this.brandCombo.setSelectedItem((String) dtm.getValueAt(row, 4));
        this.colorField.setText((dtm.getValueAt(row, 5)) == null ? "" : (dtm.getValueAt(row, 5)).toString());
        this.priceField.setText((dtm.getValueAt(row, 6)) == null ? "" : (dtm.getValueAt(row, 6)).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed

        idField.setText("");
        nameField.setText("");
        catagoryCombo.setSelectedItem("");
        brandCombo.setSelectedItem("");
        priceField.setText("");
        colorField.setText("");

    }//GEN-LAST:event_kButton10ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        idField.setText("");
        nameField.setText("");
        colorField.setText("");
        priceField.setText("");
        try {
            findAllProducts();
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select name, id from brands");
            brands_ids.add(-1);
            brands_names.add("");
            brandCombo.addItem(brands_names.get(0));
            int i = 1;
            while (rs.next()) {
                brands_names.add(rs.getString(1));
                brands_ids.add(rs.getInt(2));
                brandCombo.addItem(brands_names.get(i));
                i++;
            }
            brandCombo.setSelectedIndex(0);
            i = 1;
            rs = stmt.executeQuery("select name, id from catagories");
            catagories_ids.add(-1);
            catagories_names.add("");
            catagoryCombo.addItem(catagories_names.get(0));
            while (rs.next()) {
                catagories_names.add(rs.getString(1));
                catagories_ids.add(rs.getInt(2));
                this.catagoryCombo.addItem(catagories_names.get(i));
                i++;
            }
            catagoryCombo.setSelectedIndex(0);
            stmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void kPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kPanelFocusGained

    }//GEN-LAST:event_kPanelFocusGained

    private void kPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kPanelMouseClicked

    }//GEN-LAST:event_kPanelMouseClicked

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        new ProductReportFrame().setVisible(true);
    }//GEN-LAST:event_kButton11ActionPerformed

    private void findAllProducts() throws SQLException {
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection con = DriverManager.getConnection(Main.URL);
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select products.id, products.name, catagories.name,"
                + " brands.name, products.color, products.price from products, brands, catagories "
                + "where products.brand_id = brands.id and products.catagory_id = catagories.id");
        Main.buildTableModel(rs, jTable1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandCombo;
    private javax.swing.JComboBox<String> catagoryCombo;
    private javax.swing.JTextField colorField;
    private javax.swing.JTextField fromField;
    private javax.swing.JTextField idField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton10;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private com.k33ptoo.components.KGradientPanel kPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField searchLabel;
    private javax.swing.JTextField toField;
    // End of variables declaration//GEN-END:variables
}
