/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2021
 */
public class WarehousesPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseInPanel
     */
    public WarehousesPanel() {
        initComponents();
        LoginFrame.addPlaceHolderStyle(searchLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InnerPanel = new com.k33ptoo.components.KGradientPanel();
        toField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchLabel = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        areaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        fromField = new javax.swing.JTextField();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();

        setMinimumSize(new java.awt.Dimension(935, 448));
        setName(""); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        toField.setBackground(new java.awt.Color(102, 102, 255));
        toField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        toField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("and less than :");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Find warehouses whose area is ");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setText("Warehouses");
        jLabel1.setToolTipText("");
        jLabel1.setIconTextGap(15);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        searchLabel.setBackground(new java.awt.Color(204, 204, 255));
        searchLabel.setText("Search");
        searchLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchLabelFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Location", "Area" }));
        jComboBox1.setFocusable(false);
        jComboBox1.setMinimumSize(new java.awt.Dimension(71, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(71, 20));

        jLabel3.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel3.setText("Search by :");
        jLabel3.setMaximumSize(new java.awt.Dimension(71, 18));
        jLabel3.setMinimumSize(new java.awt.Dimension(71, 18));
        jLabel3.setPreferredSize(new java.awt.Dimension(71, 18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchLabel)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Select From Table ");

        idField.setEditable(false);
        idField.setBackground(new java.awt.Color(204, 204, 204));
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("ID :");

        locationField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("Location :");

        areaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Area :");

        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("UPDATE");
        kButton1.setBorderPainted(false);
        kButton1.setFocusPainted(false);
        kButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton1.setkBorderRadius(42);
        kButton1.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton1.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("CLEAR");
        kButton2.setBorderPainted(false);
        kButton2.setFocusPainted(false);
        kButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton2.setkForeGround(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton2.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton2.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton2.setMaximumSize(new java.awt.Dimension(111, 35));
        kButton2.setMinimumSize(new java.awt.Dimension(111, 35));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("FIND ALL");
        kButton3.setBorderPainted(false);
        kButton3.setFocusPainted(false);
        kButton3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton3.setkBorderRadius(42);
        kButton3.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton3.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton3.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton3.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton3.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setText("DELETE");
        kButton4.setBorderPainted(false);
        kButton4.setFocusPainted(false);
        kButton4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton4.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton4.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton4.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton4.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setText("find");
        kButton5.setBorderPainted(false);
        kButton5.setFocusPainted(false);
        kButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton5.setkBorderRadius(40);
        kButton5.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton5.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton5.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton5.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton5.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton5.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton5.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "Location", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(130);
        }

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("greater than :");

        fromField.setBackground(new java.awt.Color(102, 102, 255));
        fromField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        fromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFieldActionPerformed(evt);
            }
        });

        kButton6.setText("CONTENTS");
        kButton6.setBorderPainted(false);
        kButton6.setFocusPainted(false);
        kButton6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton6.setkBorderRadius(40);
        kButton6.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton6.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton6.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton6.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton6.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton6.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton6.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton7.setText("ADD");
        kButton7.setBorderPainted(false);
        kButton7.setFocusPainted(false);
        kButton7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        kButton7.setkBorderRadius(40);
        kButton7.setkEndColor(new java.awt.Color(153, 153, 153));
        kButton7.setkForeGround(new java.awt.Color(0, 0, 0));
        kButton7.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 204, 0));
        kButton7.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton7.setkPressedColor(new java.awt.Color(255, 51, 51));
        kButton7.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton7.setMaximumSize(new java.awt.Dimension(97, 47));
        kButton7.setMinimumSize(new java.awt.Dimension(97, 47));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InnerPanelLayout = new javax.swing.GroupLayout(InnerPanel);
        InnerPanel.setLayout(InnerPanelLayout);
        InnerPanelLayout.setHorizontalGroup(
            InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerPanelLayout.createSequentialGroup()
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InnerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InnerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InnerPanelLayout.createSequentialGroup()
                                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        InnerPanelLayout.setVerticalGroup(
            InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InnerPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InnerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InnerPanel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        idField.setText("");
        locationField.setText("");
        areaField.setText("");
    }//GEN-LAST:event_kButton2ActionPerformed

    private void searchLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusGained
        if(searchLabel.getText().equals("Search")){
            searchLabel.setText(null);
            searchLabel.requestFocus();
            LoginFrame.removePlaceHolderStyle(searchLabel);
        }
    }//GEN-LAST:event_searchLabelFocusGained

    private void searchLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLabelFocusLost
        if(searchLabel.getText().length()==0){
            LoginFrame.addPlaceHolderStyle(searchLabel);
            searchLabel.setText("Search");
        }
    }//GEN-LAST:event_searchLabelFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String item = ((String)jComboBox1.getSelectedItem()).toLowerCase();
        String searchText = searchLabel.getText().trim().toLowerCase();
        ResultSet rs = null;
        PreparedStatement pstmt = null;
        Connection con = null;
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            switch(item){
                case "id":
                pstmt = con.prepareStatement("select id, location, area from warehouses where id = ?");
                pstmt.setLong(1, Long.parseLong(searchText));
                rs = pstmt.executeQuery();
                break;
                case "location":
                pstmt = con.prepareStatement("select id, location, area from warehouses where lower(location) like ?");
                pstmt.setString(1, "%"+searchText+"%");
                rs = pstmt.executeQuery();
                break;
                case "area":
                    pstmt = con.prepareStatement("select id, location, area from warehouses where area = ?");
                    pstmt.setInt(1, Integer.parseInt(searchText));
                    rs = pstmt.executeQuery();
                    break;
            }
        }
        catch(SQLException e){e.printStackTrace(); JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);}
        catch(NumberFormatException e){System.err.println("NumberFormatException was caught .");}
        try{
            Main.buildTableModel(rs, jTable1);
            pstmt.close();
            con.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "nothing found");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        idField.setText("");
        locationField.setText("");
        areaField.setText("");
        try{
            findAllWarehouses();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        try{
            findAllWarehouses();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        if(idField.getText().equals("")){JOptionPane.showMessageDialog(this, "Choose a warehouse from the table", "Hint", JOptionPane.INFORMATION_MESSAGE); return; }
        Long id = Long.parseLong(idField.getText());
        String location = locationField.getText().trim();
        int area;
        if(location.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid location .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(areaField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Invalid area .", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection con = null;
        PreparedStatement stmt = null;
        try {
            area = Integer.parseInt(areaField.getText().trim());
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            stmt = con.prepareStatement("update warehouses set location = ?, area = ? where id = ?");
            stmt.setString(1, location);
            stmt.setInt(2, area);
            stmt.setLong(3, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "The warehouse updated successfully .", "Done", JOptionPane.PLAIN_MESSAGE);
            findAllWarehouses();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
            return;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid area .", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dtm = (DefaultTableModel)this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        this.idField.setText((dtm.getValueAt(row, 1)).toString());
        this.locationField.setText((dtm.getValueAt(row, 2)).toString());
        this.areaField.setText(dtm.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "You must choose from the table", "Hint", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        BigDecimal id = (BigDecimal)dtm.getValueAt(jTable1.getSelectedRow(), 1);
        Connection con = null;
        PreparedStatement ps = null;
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            con = DriverManager.getConnection(Main.URL);
            ps = con.prepareStatement("select warehouse_id from stores where warehouse_id = ?");
            ps.setBigDecimal(1, id);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "you can't delete this warehouse .. \n because it contains products", "WARNING", JOptionPane.WARNING_MESSAGE);
                ps.close();
                con.close();
                return;
            }
            if(JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this warehouse ?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
                ps.close();
                con.close();
                return;
            }
            ps = con.prepareStatement("delete from warehouses where id = ?");
            ps.setBigDecimal(1, id);
            ps.executeUpdate();
            dtm.removeRow(jTable1.getSelectedRow());
            JOptionPane.showMessageDialog(this, "The warehouse was deleted .", "Done", JOptionPane.INFORMATION_MESSAGE);
            ps.close();
            con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database.", "Oops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        if(fromField.getText().trim().equals(""))
            return;
        if(toField.getText().trim().equals(""))
            return;
        try{
            int from = Integer.parseInt(fromField.getText().trim());
            int to = Integer.parseInt(toField.getText().trim());
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            PreparedStatement stmt = con.prepareStatement("select id, location, area from warehouses where area between ? and ?");
            stmt.setInt(1, from);
            stmt.setInt(2, to);
            ResultSet rs = stmt.executeQuery();
            Main.buildTableModel(rs, jTable1);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed in connection to the database", "Oops!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid input", "Invalid input", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_kButton5ActionPerformed

    private void toFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toFieldActionPerformed

    private void fromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFieldActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        DefaultTableModel dtm1 = (DefaultTableModel) this.jTable1.getModel();
        int row = this.jTable1.getSelectedRow();
        if (row == -1) {
            return;
        }
        BigDecimal id = (BigDecimal) dtm1.getValueAt(row, 1);
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection(Main.URL);
            PreparedStatement stmt = con.prepareStatement("select stores.product_id, products.name, stores.quantity "
                    + "from stores inner join products on stores.product_id = products.id "
                    + "where stores.warehouse_id = ?");
            stmt.setBigDecimal(1, id);
            ResultSet rs = stmt.executeQuery();
            WarehouseContents contents = new WarehouseContents();
            Main.buildTableModel(rs, contents.table);
            int total = 0;
            dtm1 = (DefaultTableModel)contents.table.getModel();
            for(int i = 0; i < dtm1.getRowCount(); i++){
                total += Integer.parseInt(dtm1.getValueAt(i, 3).toString());
            }
            contents.label.setText(total + "");
            Home.glassPane.add(contents);
            Home.glassPane.setVisible(true);
            stmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "failed in connection to the database .", "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        this.setVisible(false);
        Home.addWarehousePanel.setVisible(true);
        Home.panelVisible = Home.addWarehousePanel;
    }//GEN-LAST:event_kButton7ActionPerformed

    private void findAllWarehouses() throws SQLException{
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection con = DriverManager.getConnection(Main.URL);
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select id, location, area from warehouses");
        Main.buildTableModel(rs, jTable1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel InnerPanel;
    private javax.swing.JTextField areaField;
    private javax.swing.JTextField fromField;
    private javax.swing.JTextField idField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField searchLabel;
    private javax.swing.JTextField toField;
    // End of variables declaration//GEN-END:variables
}
