--------------------------------------------------------
--  File created - Saturday-May-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BRAND_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."BRAND_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 190 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CATAGORY_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."CATAGORY_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 4 START WITH 170 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDERITEMS_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."ORDERITEMS_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 70 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDER_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."ORDER_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."PRODUCT_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 240 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STORES_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."STORES_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USER_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."USER_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence WAREHOUSE_COUNTER
--------------------------------------------------------

   CREATE SEQUENCE  "C##COMPANY"."WAREHOUSE_COUNTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 3 START WITH 140 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BRANDS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."BRANDS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATAGORIES
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."CATAGORIES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."CUSTOMERS" 
   (	"ID" NUMBER, 
	"FNAME" VARCHAR2(15 BYTE), 
	"LNAME" VARCHAR2(15 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PHONE" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERITEMS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."ORDERITEMS" 
   (	"ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"WAREHOUSE_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."ORDERS" 
   (	"ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"CUSTOMER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."PRODUCTS" 
   (	"ID" NUMBER, 
	"CATAGORY_ID" NUMBER, 
	"BRAND_ID" NUMBER, 
	"COLOR" VARCHAR2(10 BYTE), 
	"PRICE" NUMBER, 
	"NAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STORES
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."STORES" 
   (	"PRODUCT_ID" NUMBER, 
	"WAREHOUSE_ID" NUMBER, 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."USERS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WAREHOUSES
--------------------------------------------------------

  CREATE TABLE "C##COMPANY"."WAREHOUSES" 
   (	"ID" NUMBER, 
	"LOCATION" VARCHAR2(50 BYTE), 
	"AREA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##COMPANY.BRANDS
SET DEFINE OFF;
Insert into C##COMPANY.BRANDS (ID,NAME) values (110,'LG');
Insert into C##COMPANY.BRANDS (ID,NAME) values (112,'SAMSUNG');
Insert into C##COMPANY.BRANDS (ID,NAME) values (114,'LENOVO');
Insert into C##COMPANY.BRANDS (ID,NAME) values (152,'beko');
Insert into C##COMPANY.BRANDS (ID,NAME) values (156,'PHILIPS');
Insert into C##COMPANY.BRANDS (ID,NAME) values (158,'foodAppeal');
Insert into C##COMPANY.BRANDS (ID,NAME) values (160,'TCL');
Insert into C##COMPANY.BRANDS (ID,NAME) values (162,'Midea');
Insert into C##COMPANY.BRANDS (ID,NAME) values (164,'SanDisk');
Insert into C##COMPANY.BRANDS (ID,NAME) values (166,'smart');
Insert into C##COMPANY.BRANDS (ID,NAME) values (168,'magic');
Insert into C##COMPANY.BRANDS (ID,NAME) values (170,'skyworth');
Insert into C##COMPANY.BRANDS (ID,NAME) values (172,'ASUS');
Insert into C##COMPANY.BRANDS (ID,NAME) values (174,'Nikon');
Insert into C##COMPANY.BRANDS (ID,NAME) values (176,'Amica');
Insert into C##COMPANY.BRANDS (ID,NAME) values (178,'universal');
Insert into C##COMPANY.BRANDS (ID,NAME) values (180,'NUTRI-NINJA');
Insert into C##COMPANY.BRANDS (ID,NAME) values (182,'ENERGYM');
REM INSERTING into C##COMPANY.CATAGORIES
SET DEFINE OFF;
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (90,'Adel');
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (10,'Televisions');
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (14,'Ovens');
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (22,'Sports');
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (26,'Garden');
Insert into C##COMPANY.CATAGORIES (ID,NAME) values (30,'SmallHomeAppliances');
REM INSERTING into C##COMPANY.CUSTOMERS
SET DEFINE OFF;
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111114117,'test','register','tulkarm','0598745321');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111109598,'amro','sous','Tulkarm-Beitlid','0592793930');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111110459,'flan','allan','Nablus-Rafedia','0599623148');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111111561,'ahmad','kharrosha','Nablus','0599621122');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111112789,'mahmoud','ali','Tulkarm','0599781544');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111113588,'person','persons','alquds','0597991544');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (111114111,'jamal','rabee','rafah','0597991113');
Insert into C##COMPANY.CUSTOMERS (ID,FNAME,LNAME,ADDRESS,PHONE) values (123875943,'Othman','Adel','Nablus','599784622 ');
REM INSERTING into C##COMPANY.ORDERITEMS
SET DEFINE OFF;
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (44,24,29,1,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (45,25,29,2,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (50,36,26,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (51,36,23,1,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (52,37,26,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (53,38,26,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (54,38,23,1,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (55,39,23,2,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (56,40,29,1,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (58,42,35,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (59,43,41,2,208);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (57,41,29,1,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (40,13,26,1,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (22,6,23,1,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (23,6,23,1,200);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (24,7,29,3,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (30,8,26,2,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (31,9,26,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (32,9,26,1,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (33,9,23,2,200);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (34,10,23,4,200);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (35,10,23,1,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (36,11,23,1,204);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (37,11,23,2,200);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (38,12,29,3,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (39,12,26,1,210);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (41,13,23,1,200);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (42,9,29,3,205);
Insert into C##COMPANY.ORDERITEMS (ID,ORDER_ID,WAREHOUSE_ID,QUANTITY,PRODUCT_ID) values (43,9,26,3,210);
REM INSERTING into C##COMPANY.ORDERS
SET DEFINE OFF;
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (39,to_date('07-MAY-22','DD-MON-RR'),111114111);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (40,to_date('07-MAY-22','DD-MON-RR'),111114111);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (42,to_date('07-MAY-22','DD-MON-RR'),111113588);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (36,to_date('07-MAY-22','DD-MON-RR'),111112789);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (37,to_date('01-FEB-22','DD-MON-RR'),111114111);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (38,to_date('07-MAY-22','DD-MON-RR'),111112789);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (43,to_date('07-MAY-22','DD-MON-RR'),111114111);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (41,to_date('07-MAY-22','DD-MON-RR'),111114111);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (6,to_date('29-APR-22','DD-MON-RR'),111111561);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (7,to_date('20-APR-22','DD-MON-RR'),111113588);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (8,to_date('30-APR-22','DD-MON-RR'),111114117);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (9,to_date('30-APR-22','DD-MON-RR'),111111561);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (10,to_date('02-MAY-22','DD-MON-RR'),111113588);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (11,to_date('04-MAY-22','DD-MON-RR'),111109598);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (12,to_date('25-APR-22','DD-MON-RR'),111110459);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (13,to_date('20-MAR-22','DD-MON-RR'),111111561);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (24,to_date('03-MAY-22','DD-MON-RR'),123875943);
Insert into C##COMPANY.ORDERS (ID,ORDER_DATE,CUSTOMER_ID) values (25,to_date('07-MAY-22','DD-MON-RR'),123875943);
REM INSERTING into C##COMPANY.PRODUCTS
SET DEFINE OFF;
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (220,26,112,'yello',5000,'productAddingTest');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (200,30,168,'black',239,'Air-Fryer-1700W-3.5L');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (203,30,162,'black',179,'Hand-Blender-700W');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (204,30,178,'Gray',159,'Toaster-Press-1800W');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (205,10,110,null,2170,'Television-NanoCell-50Inch');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (207,10,110,null,3340,'Television-OLED-55Inch');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (208,10,170,'pink',2090,'Television-skyworth-55Inch');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (209,22,182,null,65,'Hexagonal-Dumbbell-5Kg');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (210,22,182,'Blue',29,'Jumping-Rope');
Insert into C##COMPANY.PRODUCTS (ID,CATAGORY_ID,BRAND_ID,COLOR,PRICE,NAME) values (211,22,182,null,15,'Knee-Protector-XL');
REM INSERTING into C##COMPANY.STORES
SET DEFINE OFF;
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (220,20,30);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (220,41,25);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (220,32,15);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (220,47,15);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (200,47,15);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (200,35,21);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (203,32,21);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (203,38,28);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (203,29,11);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (204,44,11);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (204,47,18);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (205,35,18);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (207,44,22);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (207,38,17);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (207,23,40);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (208,29,13);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (208,41,21);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (208,44,39);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (210,35,49);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (200,23,3);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (204,23,3);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (205,29,7);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (205,26,7);
Insert into C##COMPANY.STORES (PRODUCT_ID,WAREHOUSE_ID,QUANTITY) values (210,26,13);
REM INSERTING into C##COMPANY.USERS
SET DEFINE OFF;
Insert into C##COMPANY.USERS (ID,USERNAME,PASSWORD,EMAIL) values (61,'ahmad','123','ahmadyassin199@gmail.com');
Insert into C##COMPANY.USERS (ID,USERNAME,PASSWORD,EMAIL) values (41,'hello','123','amroosous@gmail.com');
Insert into C##COMPANY.USERS (ID,USERNAME,PASSWORD,EMAIL) values (1,'amrosous','123','amroosous@gmail.com');
Insert into C##COMPANY.USERS (ID,USERNAME,PASSWORD,EMAIL) values (21,'bahaa','789','bahaaisl566@gmail.com');
Insert into C##COMPANY.USERS (ID,USERNAME,PASSWORD,EMAIL) values (3,'testing','1234','amroosous@gmail.com');
REM INSERTING into C##COMPANY.WAREHOUSES
SET DEFINE OFF;
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (20,'Jerusalem,Salah-Eddin-St',130);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (23,'Atarot,Industrial-Area',100);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (26,'AL-Ram,Ramallah,Jarusalem-St',120);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (29,'Bethlehem,Al-Madbaseh',200);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (32,'Hebron,Wadi-AL-Tuffah',200);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (35,'Ramallah,AL-Irsal-St',300);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (38,'AL-Bireh,Nablus-St',260);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (41,'Nablus,Rafedia_St',300);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (44,'Jericho,AL-Quds_St',350);
Insert into C##COMPANY.WAREHOUSES (ID,LOCATION,AREA) values (47,'Jenin,AL-Nasreh_St',185);
--------------------------------------------------------
--  DDL for Index BRANDS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."BRANDS_ID_PK" ON "C##COMPANY"."BRANDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATAGORIES_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."CATAGORIES_ID_PK" ON "C##COMPANY"."CATAGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."CUSTOMERS_ID_PK" ON "C##COMPANY"."CUSTOMERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERITEMS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."ORDERITEMS_ID_PK" ON "C##COMPANY"."ORDERITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."ORDERS_ID_PK" ON "C##COMPANY"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."PRODUCTS_ID_PK" ON "C##COMPANY"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."STORES_PK" ON "C##COMPANY"."STORES" ("PRODUCT_ID", "WAREHOUSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WAREHOUSES_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##COMPANY"."WAREHOUSES_ID_PK" ON "C##COMPANY"."WAREHOUSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger DELETE_ITEM
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##COMPANY"."DELETE_ITEM" 
before delete on orderitems
for each row
begin
update stores set stores.quantity = stores.quantity + :old.quantity where 
stores.product_id = :old.product_id and stores.warehouse_id = :old.warehouse_id;
end;
/
ALTER TRIGGER "C##COMPANY"."DELETE_ITEM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBTRACT_QUANTITY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##COMPANY"."SUBTRACT_QUANTITY" 
before insert on orderitems
for each row
DECLARE
warehouse_quantity number;
begin
select distinct stores.quantity into warehouse_quantity from stores where (stores.product_id = :new.product_id and stores.warehouse_id = :new.warehouse_id);
if (:new.quantity <= warehouse_quantity) then
update stores set stores.quantity = stores.quantity - :new.quantity where 
stores.product_id = :new.product_id and stores.warehouse_id = :new.warehouse_id;
else 
raise_application_error(-20502, 'this warehouse does not have the needed quantity for this product');
                                 end if;
exception 
when no_data_found then dbms_output.put_line('no data found');
when too_many_rows then dbms_output.put_line('too many rows');

end;
/
ALTER TRIGGER "C##COMPANY"."SUBTRACT_QUANTITY" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERITEMS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."ORDERITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."ORDERITEMS" MODIFY ("WAREHOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."ORDERITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."ORDERITEMS" ADD CONSTRAINT "ORDERITEMS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."ORDERITEMS_ID_PK"  ENABLE;
  ALTER TABLE "C##COMPANY"."ORDERITEMS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANDS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."BRANDS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."BRANDS" ADD CONSTRAINT "BRANDS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."BRANDS_ID_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATAGORIES
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."CATAGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."CATAGORIES" ADD CONSTRAINT "CATAGORIES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."CATAGORIES_ID_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."ORDERS" ADD CONSTRAINT "ORDERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."ORDERS_ID_PK"  ENABLE;
  ALTER TABLE "C##COMPANY"."ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."ORDERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."CUSTOMERS" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."CUSTOMERS" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."CUSTOMERS_ID_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORES
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."STORES" ADD CONSTRAINT "STORES_PK" PRIMARY KEY ("PRODUCT_ID", "WAREHOUSE_ID")
  USING INDEX "C##COMPANY"."STORES_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WAREHOUSES
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."WAREHOUSES" ADD CONSTRAINT "WAREHOUSES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."WAREHOUSES_ID_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##COMPANY"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX "C##COMPANY"."PRODUCTS_ID_PK"  ENABLE;
  ALTER TABLE "C##COMPANY"."PRODUCTS" MODIFY ("CATAGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."PRODUCTS" MODIFY ("BRAND_ID" NOT NULL ENABLE);
  ALTER TABLE "C##COMPANY"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDERITEMS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."ORDERITEMS" ADD CONSTRAINT "ORDERITEMS_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "C##COMPANY"."PRODUCTS" ("ID") ENABLE;
  ALTER TABLE "C##COMPANY"."ORDERITEMS" ADD CONSTRAINT "ORDERITEMS_WAREHOUSE_ID_FK" FOREIGN KEY ("WAREHOUSE_ID")
	  REFERENCES "C##COMPANY"."WAREHOUSES" ("ID") ENABLE;
  ALTER TABLE "C##COMPANY"."ORDERITEMS" ADD CONSTRAINT "ORDERITEMS_ORDER_ID_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "C##COMPANY"."ORDERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."ORDERS" ADD CONSTRAINT "ORDERS_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "C##COMPANY"."CUSTOMERS" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_BRAND_ID_FK" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "C##COMPANY"."BRANDS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##COMPANY"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_CATAGORY_ID_FK" FOREIGN KEY ("CATAGORY_ID")
	  REFERENCES "C##COMPANY"."CATAGORIES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORES
--------------------------------------------------------

  ALTER TABLE "C##COMPANY"."STORES" ADD CONSTRAINT "STORES_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "C##COMPANY"."PRODUCTS" ("ID") ENABLE;
  ALTER TABLE "C##COMPANY"."STORES" ADD CONSTRAINT "STORES_WAREHOUSE_ID_FK" FOREIGN KEY ("WAREHOUSE_ID")
	  REFERENCES "C##COMPANY"."WAREHOUSES" ("ID") ENABLE;
